import { BEACH_OBJECT_TYPES } from "../objects/beachObjectCatalog.js";

export const BUILDING_ROLE_IDS = Object.freeze({
  ATTRACTS_VISITORS: "attractsVisitors",
  CONTROLS_LITTER: "controlsLitter",
  GENERATES_REVENUE: "generatesRevenue",
  INCREASES_RETENTION: "increasesRetention",
  IMPROVES_SATISFACTION: "improvesSatisfaction",
  REQUIRES_MAINTENANCE: "requiresMaintenance"
});

const BUILDING_ROLE_IDS_BY_TYPE = Object.freeze({
  [BEACH_OBJECT_TYPES.BEVERAGE_STORE]: Object.freeze([
    BUILDING_ROLE_IDS.GENERATES_REVENUE
  ]),
  [BEACH_OBJECT_TYPES.LIFEGUARD_BUILDING]: Object.freeze([
    BUILDING_ROLE_IDS.IMPROVES_SATISFACTION,
    BUILDING_ROLE_IDS.REQUIRES_MAINTENANCE
  ]),
  [BEACH_OBJECT_TYPES.WIFI_SPOT]: Object.freeze([
    BUILDING_ROLE_IDS.GENERATES_REVENUE,
    BUILDING_ROLE_IDS.IMPROVES_SATISFACTION
  ]),
  [BEACH_OBJECT_TYPES.TOILET_BUILDING]: Object.freeze([
    BUILDING_ROLE_IDS.INCREASES_RETENTION,
    BUILDING_ROLE_IDS.IMPROVES_SATISFACTION,
    BUILDING_ROLE_IDS.REQUIRES_MAINTENANCE
  ]),
  [BEACH_OBJECT_TYPES.TRASH_CANS]: Object.freeze([
    BUILDING_ROLE_IDS.CONTROLS_LITTER
  ]),
  [BEACH_OBJECT_TYPES.VOLLEYBALL_COURT]: Object.freeze([
    BUILDING_ROLE_IDS.IMPROVES_SATISFACTION
  ]),
  [BEACH_OBJECT_TYPES.SUN_SHADE]: Object.freeze([
    BUILDING_ROLE_IDS.ATTRACTS_VISITORS,
    BUILDING_ROLE_IDS.INCREASES_RETENTION
  ])
});

export function getBuildingRoleIds(buildingType) {
  return BUILDING_ROLE_IDS_BY_TYPE[buildingType] || Object.freeze([]);
}
