export const TREE_REVIVAL_LEAF_BURST_BASE_HEIGHT = 1.16;
export const TREE_REVIVAL_LEAF_BURST_HEIGHT_RANGE = 0.86;
export const TREE_REVIVAL_LEAF_BURST_GRAVITY = 0.54;
export const TREE_REVIVAL_LEAF_BURST_DRIFT = 0.68;
export const TREE_REVIVAL_LEAF_BURST_SIZE_MIN = 0.22;
export const TREE_REVIVAL_LEAF_BURST_SIZE_MAX = 0.42;

export const LANDSCAPE_CUT_EFFECT_DURATION = 0.46;
export const LANDSCAPE_CUT_EFFECT_LERP_PORTION = 0.62;
export const LANDSCAPE_CUT_EFFECT_LIFT = 0.13;
export const LANDSCAPE_CUT_EFFECT_POP_SCALE = 1.18;

export const FIELD_MOVE_INVALID_GROUND_CELL_RADIUS_FACTOR = 0.82;

export const PLAYER_COUNTER_PROMPT_DURATION_MS = 1500;
export const PLAYER_INTERACTION_WORLD_PROMPT_TARGET_IDS = new Set(["tangrowth", "squirtle"]);

export const LEAF_RESOURCE_BILLBOARD_SIZE = Object.freeze([0.72, 0.72]);
export const LEAF_RESOURCE_BILLBOARD_Y_OFFSET = 0.32;

export const CAMPFIRE_WOOD_PILE_SIZE = Object.freeze([0.52, 0.38]);

export const TRAIN_HOUSE_MUSIC_FULL_DISTANCE = 1.25;
export const TRAIN_HOUSE_MUSIC_FADE_DISTANCE = 16.4;
export const TRAIN_HOUSE_MUSIC_MAX_VOLUME = 0.74;

export const TRAIN_HOUSE_DANCE_SIDE_SWAY = 0.055;
export const TRAIN_HOUSE_DANCE_FORWARD_SWAY = 0.025;
export const TRAIN_HOUSE_DANCE_SCALE_PULSE = 0.045;
export const TRAIN_HOUSE_DANCE_YAW_SWAY = 0.06;
export const TRAIN_HOUSE_DANCE_TOP_SWAY = 0.08;

export const INTERACTION_INFO_ICON_SIZE = Object.freeze([0.72, 0.72]);
export const WORKBENCH_INFO_ICON_OFFSET = Object.freeze([1.42, 1.34, -0.42]);

export const WORKBENCH_GREEN_ARROW_OFFSET = Object.freeze([0, 2.18, 0]);
export const WORKBENCH_GREEN_ARROW_BASE_SCALE = 3;
export const WORKBENCH_GREEN_ARROW_BOB_HEIGHT = 0.16;
export const WORKBENCH_GREEN_ARROW_BOB_SPEED = 2.7;
export const WORKBENCH_GREEN_ARROW_YAW_SWAY = 0.18;
export const WORKBENCH_GREEN_ARROW_YAW_SPEED = 1.9;
export const WORKBENCH_GREEN_ARROW_ROLL_SWAY = 0.045;
export const WORKBENCH_GREEN_ARROW_ROLL_SPEED = 2.4;