// app/runtime/fieldMoveRuntime/fieldMoveTuning.js

import { ACT_TWO_PLAYER_SPEED } from "../../session/configurePlayerSpawner.js";

export const TIMBURR_BUILD_BLOCK_SPEED = ACT_TWO_PLAYER_SPEED;
export const TIMBURR_BUILD_BLOCK_STAND_DISTANCE = 1.04;
export const TIMBURR_BUILD_BLOCK_ARRIVE_DISTANCE = 0.08;
export const TIMBURR_BUILD_BLOCK_CAST_DURATION = 0.42;
export const TIMBURR_BUILD_BLOCK_IMPACT_TIME = 0.16;

export const SQUIRTLE_WATER_GUN_SPEED = 4.8;
export const SQUIRTLE_WATER_GUN_STAND_DISTANCE = 1.18;
export const SQUIRTLE_WATER_GUN_ARRIVE_DISTANCE = 0.08;
export const SQUIRTLE_WATER_GUN_SPRAY_DURATION = 0.82;
export const SQUIRTLE_WATER_GUN_IMPACT_TIME = 0.34;
export const SQUIRTLE_WATER_GUN_ARC_HEIGHT = 0.86;
export const SQUIRTLE_WATER_GUN_PARTICLE_COUNT = 24;
export const SQUIRTLE_WATER_GUN_STREAM_LANE_COUNT = 5;
export const SQUIRTLE_WATER_GUN_STREAM_WIDTH = 0.05;
export const SQUIRTLE_WATER_GUN_SPLASH_PARTICLE_COUNT = 18;
export const SQUIRTLE_WATER_GUN_SPLASH_DURATION = 0.52;
export const SQUIRTLE_WATER_GUN_SPLASH_RADIUS = 0.86;
export const SQUIRTLE_WATER_GUN_USE_COUNT_FLAG = "squirtleWaterGunUseCount";
export const SQUIRTLE_WATER_GUN_BASE_LEVEL = 11;
export const SQUIRTLE_WATER_GUN_USES_PER_LEVEL = 3;
export const SQUIRTLE_WATER_GUN_EVOLUTION_MAX_USES = 24;
export const SQUIRTLE_WATER_GUN_MAX_SPEED_MULTIPLIER = 1.7;
export const SQUIRTLE_WATER_GUN_MIN_SPRAY_DURATION = 0.46;
export const SQUIRTLE_WATER_GUN_MIN_IMPACT_TIME = 0.18;

export const SQUIRTLE_WATER_STAMINA_MAX = 3;
export const SQUIRTLE_WATER_STAMINA_COST = 1;
export const SQUIRTLE_WATER_STAMINA_RECHARGE_DURATION = 3.2;
export const SQUIRTLE_WATER_STAMINA_BAR_WIDTH = 1.72;
export const SQUIRTLE_WATER_STAMINA_BAR_HEIGHT = 0.2;
export const SQUIRTLE_WATER_STAMINA_VISUAL_DECREASE_DURATION = 0.28;
export const SQUIRTLE_WATER_STAMINA_VISUAL_INCREASE_DURATION = 0.16;

export const SQUIRTLE_CHARGING_PARTICLE_COUNT = 14;
export const SQUIRTLE_CHARGING_PARTICLE_RADIUS = 0.72;
export const SQUIRTLE_CHARGING_PARTICLE_DURATION = 1.15;

export const BULBASAUR_LEAFAGE_SPEED = 2.25;
export const BULBASAUR_LEAFAGE_STAND_DISTANCE = 1.04;
export const BULBASAUR_LEAFAGE_ARRIVE_DISTANCE = 0.08;
export const BULBASAUR_LEAFAGE_CAST_DURATION = 0.58;
export const BULBASAUR_LEAFAGE_IMPACT_TIME = 0.22;
export const BULBASAUR_LEAFAGE_PARTICLE_COUNT = 24;
export const BULBASAUR_LEAFAGE_STREAM_WIDTH = 0.18;
export const BULBASAUR_LEAFAGE_ARC_HEIGHT = 0.46;
export const BULBASAUR_LEAFAGE_PARTICLE_SIZE_MIN = 0.18;
export const BULBASAUR_LEAFAGE_PARTICLE_SIZE_MAX = 0.34;
export const BULBASAUR_LEAFAGE_BURST_PARTICLE_COUNT = 18;
export const BULBASAUR_LEAFAGE_BURST_DURATION = 0.46;
export const BULBASAUR_LEAFAGE_BURST_RADIUS = 0.72;

export const CHARMANDER_FIRE_SPEED = 4.2;
export const CHARMANDER_FIRE_STAND_DISTANCE = 1.72;
export const CHARMANDER_FIRE_ARRIVE_DISTANCE = 0.08;
export const CHARMANDER_FIRE_SPRAY_DURATION = 1.44;
export const CHARMANDER_FIRE_IMPACT_TIME = 0.56;
export const CHARMANDER_FIRE_VISUAL_SCALE = 3;
export const CHARMANDER_FIRE_ARC_HEIGHT = 0.42 * CHARMANDER_FIRE_VISUAL_SCALE;
export const CHARMANDER_FIRE_PARTICLE_COUNT = 30;
export const CHARMANDER_FIRE_PARTICLE_LIFETIME_MIN = 0.2;
export const CHARMANDER_FIRE_PARTICLE_LIFETIME_MAX = 1;
export const CHARMANDER_FIRE_PARTICLE_SIZE_MIN = 0.2 * CHARMANDER_FIRE_VISUAL_SCALE;
export const CHARMANDER_FIRE_PARTICLE_SIZE_MAX = 0.4 * CHARMANDER_FIRE_VISUAL_SCALE;
export const CHARMANDER_FIRE_CONE_RADIUS = 0.1813 * CHARMANDER_FIRE_VISUAL_SCALE;
export const CHARMANDER_FIRE_NOISE_STRENGTH = 0.09 * CHARMANDER_FIRE_VISUAL_SCALE;
export const CHARMANDER_FIRE_NOISE_POSITION_AMOUNT = 0.191 * CHARMANDER_FIRE_VISUAL_SCALE;
export const CHARMANDER_FIRE_NOISE_ROTATION_AMOUNT = 1.677;
export const CHARMANDER_FIRE_BURST_PARTICLE_COUNT = 16;
export const CHARMANDER_FIRE_BURST_DURATION = 0.84;
export const CHARMANDER_FIRE_BURST_RADIUS = 0.74 * CHARMANDER_FIRE_VISUAL_SCALE;

export const CHARMANDER_CARBON_BAR_WIDTH = 1.72;
export const CHARMANDER_CARBON_BAR_HEIGHT = 0.2;
export const CHARMANDER_CARBON_BAR_Y_OFFSET = 1.18;
export const CHARMANDER_CARBON_BAR_FILL_DEPTH_OFFSET = 0.035;
export const CHARMANDER_CARBON_VISUAL_DECREASE_DURATION = 0.24;
export const CHARMANDER_CARBON_VISUAL_INCREASE_DURATION = 0.18;