import { BATHER_PROBLEM_SOURCES } from "../npcs/npcSystem.js";

const NEED_LABEL_BY_SOURCE = Object.freeze({
  [BATHER_PROBLEM_SOURCES.HEAT]: "NEEDS A DRINK!",
  [BATHER_PROBLEM_SOURCES.ENTERTAINMENT]: "IS BORED!",
  [BATHER_PROBLEM_SOURCES.WIFI]: "WANTS WI-FI!",
  [BATHER_PROBLEM_SOURCES.TOILET]: "NEEDS A TOILET!"
});
const BEACH_PROBLEM_LABEL_BY_SOURCE = Object.freeze({
  [BATHER_PROBLEM_SOURCES.HEAT]: "BATHERS NEED DRINKS!",
  [BATHER_PROBLEM_SOURCES.ENTERTAINMENT]: "BATHERS ARE BORED!",
  [BATHER_PROBLEM_SOURCES.WIFI]: "BATHERS WANT WI-FI!",
  [BATHER_PROBLEM_SOURCES.TOILET]: "BATHERS NEED TOILETS!"
});

export function presentBatherNeedFeedback(source) {
  return NEED_LABEL_BY_SOURCE[source] || "BATHER IS UPSET!";
}

export function presentBeachProblemFeedback(source) {
  return BEACH_PROBLEM_LABEL_BY_SOURCE[source] || "BATHERS WERE UPSET!";
}
